export const carouselData = [
	{
		src: 'https://media.vov.vn/sites/default/files/styles/large_watermark/public/2023-12/ba_mai_thi_y_nhi_giam_doc_kinh_doanh_cong_ty_tnhh_my_phuong_foods_cho_biet_san_pham_banh_dua_nuong_duoc_chung_nhan_4_sao_va_tiem_nang_5_sao._.png.jpg',
		alt: 'anh1',
		width: 100,
		height: 100,
	},
	{
		src: 'https://media.vov.vn/sites/default/files/styles/large_watermark/public/2023-12/ba_mai_thi_y_nhi_giam_doc_kinh_doanh_cong_ty_tnhh_my_phuong_foods_cho_biet_san_pham_banh_dua_nuong_duoc_chung_nhan_4_sao_va_tiem_nang_5_sao._.png.jpg',
		alt: 'anh1',
		width: 100,
		height: 100,
	},
	{
		src: 'https://media.vov.vn/sites/default/files/styles/large_watermark/public/2023-12/ba_mai_thi_y_nhi_giam_doc_kinh_doanh_cong_ty_tnhh_my_phuong_foods_cho_biet_san_pham_banh_dua_nuong_duoc_chung_nhan_4_sao_va_tiem_nang_5_sao._.png.jpg',
		alt: 'anh1',
		width: 100,
		height: 100,
	},
	{
		src: 'https://media.vov.vn/sites/default/files/styles/large_watermark/public/2023-12/ba_mai_thi_y_nhi_giam_doc_kinh_doanh_cong_ty_tnhh_my_phuong_foods_cho_biet_san_pham_banh_dua_nuong_duoc_chung_nhan_4_sao_va_tiem_nang_5_sao._.png.jpg',
		alt: 'anh1',
		width: 100,
		height: 100,
	},
];

export const productsData = [
	{
		id: 1,
		img: 'https://media.vov.vn/sites/default/files/styles/large_watermark/public/2023-12/ba_mai_thi_y_nhi_giam_doc_kinh_doanh_cong_ty_tnhh_my_phuong_foods_cho_biet_san_pham_banh_dua_nuong_duoc_chung_nhan_4_sao_va_tiem_nang_5_sao._.png.jpg',
		name: 'Product Name',
		description: 'Product description goes here.',
		price: 20.0,
		discount: 25.0,
		discountPercentage: 20,
	},
	{
		id: 2,
		img: 'https://media.vov.vn/sites/default/files/styles/large_watermark/public/2023-12/ba_mai_thi_y_nhi_giam_doc_kinh_doanh_cong_ty_tnhh_my_phuong_foods_cho_biet_san_pham_banh_dua_nuong_duoc_chung_nhan_4_sao_va_tiem_nang_5_sao._.png.jpg',
		name: 'Product Name',
		description: 'Product description goes here.',
		price: 20.0,
		discount: 25.0,
		discountPercentage: 20,
	},
	{
		id: 3,
		img: 'https://media.vov.vn/sites/default/files/styles/large_watermark/public/2023-12/ba_mai_thi_y_nhi_giam_doc_kinh_doanh_cong_ty_tnhh_my_phuong_foods_cho_biet_san_pham_banh_dua_nuong_duoc_chung_nhan_4_sao_va_tiem_nang_5_sao._.png.jpg',
		name: 'Product Name',
		description: 'Product description goes here.',
		price: 20.0,
		discount: 25.0,
		discountPercentage: 20,
	},
	{
		id: 4,
		img: 'https://media.vov.vn/sites/default/files/styles/large_watermark/public/2023-12/ba_mai_thi_y_nhi_giam_doc_kinh_doanh_cong_ty_tnhh_my_phuong_foods_cho_biet_san_pham_banh_dua_nuong_duoc_chung_nhan_4_sao_va_tiem_nang_5_sao._.png.jpg',
		name: 'Product Name',
		description: 'Product description goes here.',
		price: 20.0,
		discount: 25.0,
		discountPercentage: 20,
	},
	{
		id: 5,
		img: 'https://media.vov.vn/sites/default/files/styles/large_watermark/public/2023-12/ba_mai_thi_y_nhi_giam_doc_kinh_doanh_cong_ty_tnhh_my_phuong_foods_cho_biet_san_pham_banh_dua_nuong_duoc_chung_nhan_4_sao_va_tiem_nang_5_sao._.png.jpg',
		name: 'Product Name',
		description: 'Product description goes here.',
		price: 20.0,
		discount: 25.0,
		discountPercentage: 20,
	},
	{
		img: 'https://media.vov.vn/sites/default/files/styles/large_watermark/public/2023-12/ba_mai_thi_y_nhi_giam_doc_kinh_doanh_cong_ty_tnhh_my_phuong_foods_cho_biet_san_pham_banh_dua_nuong_duoc_chung_nhan_4_sao_va_tiem_nang_5_sao._.png.jpg',
		name: 'Product Name',
		description: 'Product description goes here.',
		price: 20.0,
		discount: 25.0,
		discountPercentage: 20,
	},
	{
		img: 'https://media.vov.vn/sites/default/files/styles/large_watermark/public/2023-12/ba_mai_thi_y_nhi_giam_doc_kinh_doanh_cong_ty_tnhh_my_phuong_foods_cho_biet_san_pham_banh_dua_nuong_duoc_chung_nhan_4_sao_va_tiem_nang_5_sao._.png.jpg',
		name: 'Product Name',
		description: 'Product description goes here.',
		price: 20.0,
		discount: 25.0,
		discountPercentage: 20,
	},
	{
		img: 'https://media.vov.vn/sites/default/files/styles/large_watermark/public/2023-12/ba_mai_thi_y_nhi_giam_doc_kinh_doanh_cong_ty_tnhh_my_phuong_foods_cho_biet_san_pham_banh_dua_nuong_duoc_chung_nhan_4_sao_va_tiem_nang_5_sao._.png.jpg',
		name: 'Product Name',
		description: 'Product description goes here.',
		price: 20.0,
		discount: 25.0,
		discountPercentage: 20,
	},
	{
		img: 'https://media.vov.vn/sites/default/files/styles/large_watermark/public/2023-12/ba_mai_thi_y_nhi_giam_doc_kinh_doanh_cong_ty_tnhh_my_phuong_foods_cho_biet_san_pham_banh_dua_nuong_duoc_chung_nhan_4_sao_va_tiem_nang_5_sao._.png.jpg',
		name: 'Product Name',
		description: 'Product description goes here.',
		price: 20.0,
		discount: 25.0,
		discountPercentage: 20,
	},
];
